/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import connection.ConnectionFactory;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.bean.Itens;
import model.bean.Usuario;
import model.dao.ItensDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author PICHAU
 */
public class TelaInvAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaInvUsu
     */
    private Connection con = null;

    public TelaInvAdm() {
        con = ConnectionFactory.getConnection();
        initComponents();

        lbInventario.setEnabled(false);
        PainelItens1.setVisible(true);
        lbUsuario.setEnabled(true);
        PainelUsuarios.setVisible(false);

        attTabelaItens();
        
        //imgEB1.setEnabled(false);
        imgEB2.setEnabled(false);
        imgEB4.setEnabled(false);

    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

//            Color color1 = new Color(48, 18, 78); Cor Laranja
//            Color color2 = new Color(200, 88, 51); Cor Roxa
            Color color1 = new Color(21, 170, 30);
            Color color2 = new Color(10, 75, 15);
            GradientPaint gp = new GradientPaint(0, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PainelItens1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbItens1 = new javax.swing.JTable();
        PainelConfigItens = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeItem1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDescricaoItem1 = new javax.swing.JTextArea();
        cbCategoria1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtEspecItem1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAddItens = new javax.swing.JButton();
        btnEditarItens = new javax.swing.JButton();
        btnExcluirItens = new javax.swing.JButton();
        imgEB2 = new javax.swing.JLabel();
        campoBuscaItens = new javax.swing.JTextField();
        imgPesq = new javax.swing.JLabel();
        imgEB1 = new javax.swing.JLabel();
        PainelUsuarios = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        PainelConfigUser = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeUsu = new javax.swing.JTextField();
        cbTipoUsu = new javax.swing.JComboBox<>();
        txtSenhaUsu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAddUsu = new javax.swing.JButton();
        btnEditarUsu = new javax.swing.JButton();
        btnExcluirUsu = new javax.swing.JButton();
        imgEB4 = new javax.swing.JLabel();
        campoBuscaUser = new javax.swing.JTextField();
        imgPesq1 = new javax.swing.JLabel();
        imgEB3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelCabeçalho = new jPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDeslogar = new javax.swing.JButton();
        logoEBMini = new javax.swing.JLabel();
        imgEBMedal = new javax.swing.JLabel();
        lbInventario = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        imgEB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 90));

        PainelItens1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelItens1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbItens1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição", "Categoria", "Especificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbItens1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItens1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbItens1);

        PainelItens1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 840, 260));

        PainelConfigItens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelConfigItens.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOME");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel8.add(txtNomeItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DESCRIÇÃO");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        taDescricaoItem1.setColumns(20);
        taDescricaoItem1.setRows(5);
        taDescricaoItem1.setText("\n\n");
        jScrollPane5.setViewportView(taDescricaoItem1);

        jPanel8.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 390, 130));

        cbCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Eletronico", "Movel", "Material de Escritório" }));
        jPanel8.add(cbCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CATEGORIA");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));
        jPanel8.add(txtEspecItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 230, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ESPECIFICAÇAO");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 20));

        btnAddItens.setText("ADICIONAR");
        btnAddItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItensActionPerformed(evt);
            }
        });
        jPanel8.add(btnAddItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, 20));

        btnEditarItens.setText("EDITAR");
        btnEditarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarItensActionPerformed(evt);
            }
        });
        jPanel8.add(btnEditarItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 20));

        btnExcluirItens.setText("EXCLUIR");
        btnExcluirItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItensActionPerformed(evt);
            }
        });
        jPanel8.add(btnExcluirItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 172, 91, 20));

        imgEB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EBGrande.jpg"))); // NOI18N
        jPanel8.add(imgEB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, -380, 1070, 630));

        PainelConfigItens.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 200));

        PainelItens1.add(PainelConfigItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 840, 220));

        campoBuscaItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaItensjTextField_pesqActionPerformed(evt);
            }
        });
        campoBuscaItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaItensKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaItensKeyTyped(evt);
            }
        });
        PainelItens1.add(campoBuscaItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 720, 30));

        imgPesq.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        imgPesq.setForeground(new java.awt.Color(255, 255, 255));
        imgPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconePesq.png"))); // NOI18N
        imgPesq.setText("Pesquisar");
        PainelItens1.add(imgPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 30));

        imgEB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EBGrande.jpg"))); // NOI18N
        PainelItens1.add(imgEB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -10, 1070, 630));

        jPanel1.add(PainelItens1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 860, 590));

        PainelUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Senha", "Tipo Autenticação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbUsuarios);

        PainelUsuarios.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 840, 270));

        PainelConfigUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelConfigUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOME");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel5.add(txtNomeUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 30));

        cbTipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Admin", "Usuario" }));
        jPanel5.add(cbTipoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 130, 30));
        jPanel5.add(txtSenhaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SENHA");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TIPO USUARIO");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        btnAddUsu.setText("ADICIONAR");
        btnAddUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUsuActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        btnEditarUsu.setText("EDITAR");
        btnEditarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 90, 20));

        btnExcluirUsu.setText("EXCLUIR");
        btnExcluirUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuActionPerformed(evt);
            }
        });
        jPanel5.add(btnExcluirUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 91, 20));

        imgEB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EBGrande.jpg"))); // NOI18N
        jPanel5.add(imgEB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, -380, 1070, 630));

        PainelConfigUser.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 170));

        PainelUsuarios.add(PainelConfigUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 840, 190));

        campoBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaUserjTextField_pesqActionPerformed(evt);
            }
        });
        campoBuscaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyTyped(evt);
            }
        });
        PainelUsuarios.add(campoBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 720, 30));

        imgPesq1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        imgPesq1.setForeground(new java.awt.Color(255, 255, 255));
        imgPesq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconePesq.png"))); // NOI18N
        imgPesq1.setText("Pesquisar");
        PainelUsuarios.add(imgPesq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 30));

        imgEB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EBGrande.jpg"))); // NOI18N
        PainelUsuarios.add(imgEB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -10, 1070, 630));

        jLabel5.setText("jLabel5");
        PainelUsuarios.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jPanel1.add(PainelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 860, 590));

        jPanelCabeçalho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanelCabeçalho.setForeground(new java.awt.Color(255, 255, 255));
        jPanelCabeçalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 122, 56));
        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISCOFIS");
        jPanelCabeçalho.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA DE CONTROLE FISICO");
        jPanelCabeçalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btnDeslogar.setBackground(new java.awt.Color(204, 204, 204));
        btnDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout.png"))); // NOI18N
        btnDeslogar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });
        jPanelCabeçalho.add(btnDeslogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 40, 40));

        logoEBMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo EB Miniatura.png"))); // NOI18N
        jPanelCabeçalho.add(logoEBMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 100));

        imgEBMedal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SimboloEBRecortado.png"))); // NOI18N
        jPanelCabeçalho.add(imgEBMedal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 349, 99));

        jPanel1.add(jPanelCabeçalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        lbInventario.setBackground(new java.awt.Color(255, 255, 255));
        lbInventario.setForeground(new java.awt.Color(51, 51, 51));
        lbInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Inventario2.jpg"))); // NOI18N
        lbInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInventarioMouseClicked(evt);
            }
        });
        jPanel1.add(lbInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lbUsuario.setBackground(new java.awt.Color(51, 51, 255));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Users.jpg"))); // NOI18N
        lbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        imgEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EBGrande.jpg"))); // NOI18N
        jPanel1.add(imgEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 100, 1070, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão" + ex);
        }
        LoginUsu telalogin = new LoginUsu();
        telalogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeslogarActionPerformed

    private void btnAddUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsuActionPerformed
        // TODO add your handling code here:
        Usuario objUsu = new Usuario();
        UsuarioDAO objUsuDAO = new UsuarioDAO();

        String indexComboBox = (String) cbTipoUsu.getSelectedItem();

        while (txtNomeUsu.getText().equals("") || txtSenhaUsu.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            break;
        }
        if (indexComboBox.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria");
        } else {

            objUsu.setNome_Usu(txtNomeUsu.getText());
            objUsu.setSenha_Usu(txtSenhaUsu.getText());
            objUsu.setTipo_Usu(indexComboBox);

            objUsuDAO.save(objUsu);
            JOptionPane.showMessageDialog(null, "Item '" + txtNomeUsu.getText() + "' foi cadastrado com sucesso !");
            attTabelaUsu();
        }
        txtNomeUsu.setText("");
        txtSenhaUsu.setText("");
        cbTipoUsu.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddUsuActionPerformed

    private void btnEditarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuActionPerformed
        // TODO add your handling code here:
        if (tbUsuarios.getSelectedRow() != -1) {

            String indexComboBox = (String) cbTipoUsu.getSelectedItem();

            if (indexComboBox.equals("Selecione")) {
                JOptionPane.showMessageDialog(null, "Selecione um tipo de usuario ");
            } else {

                Usuario objUsu = new Usuario();
                UsuarioDAO objUsuDAO = new UsuarioDAO();

                objUsu.setId_Usu((int) tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 0));
                objUsu.setNome_Usu(txtNomeUsu.getText());
                objUsu.setSenha_Usu(txtSenhaUsu.getText());
                objUsu.setTipo_Usu(indexComboBox);

                objUsuDAO.updateUsu(objUsu);

                attTabelaUsu();

                txtNomeUsu.setText("");
                txtSenhaUsu.setText("");
                cbTipoUsu.setSelectedIndex(0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_btnEditarUsuActionPerformed

    private void btnExcluirUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuActionPerformed
        // TODO add your handling code here:
        if (tbUsuarios.getSelectedRow() != -1) {

            int row = tbUsuarios.getSelectedRow();
            String titulo = tbUsuarios.getModel().getValueAt(row, 1).toString();
            int result = JOptionPane.showConfirmDialog(null, "ATENÇÃO ! Deseja excluir o Usuario: " + titulo + " ?");

            if (result == 0) {

                String cell = tbUsuarios.getModel().getValueAt(row, 0).toString();
                String sql = "DELETE FROM usu WHERE id_Usu = " + cell;
                try {
                    PreparedStatement stmt = con.prepareStatement(sql);
                    stmt.execute();
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                    attTabelaItens();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao Excluir" + e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Item");
        }
        attTabelaUsu();
    }//GEN-LAST:event_btnExcluirUsuActionPerformed

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // TODO add your handling code here:
        if (tbUsuarios.getSelectedRow() != -1) {
            txtNomeUsu.setText(tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 1).toString());
            cbTipoUsu.setSelectedIndex(0);
            txtSenhaUsu.setText(tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void lbInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInventarioMouseClicked
        // TODO add your handling code here:
        lbInventario.setEnabled(false);
        PainelItens1.setVisible(true);

        lbUsuario.setEnabled(true);
        PainelUsuarios.setVisible(false);
        attTabelaItens();
    }//GEN-LAST:event_lbInventarioMouseClicked

    private void lbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuarioMouseClicked
        // TODO add your handling code here:
        lbInventario.setEnabled(true);
        PainelItens1.setVisible(false);

        lbUsuario.setEnabled(false);
        PainelUsuarios.setVisible(true);
        attTabelaUsu();
    }//GEN-LAST:event_lbUsuarioMouseClicked

    private void btnExcluirItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItensActionPerformed
        // TODO add your handling code here:
        if (tbItens1.getSelectedRow() != -1) {

            int row = tbItens1.getSelectedRow();
            String cell = tbItens1.getModel().getValueAt(row, 0).toString();

            String titulo = tbItens1.getModel().getValueAt(row, 1).toString();
            int result = JOptionPane.showConfirmDialog(null, "ATENÇÃO ! Deseja excluir o Item: " + titulo + " ?");

            if (result == 0) {

                String sql = "DELETE FROM Item WHERE id_Item = " + cell;

                try {

                    PreparedStatement stmt = con.prepareStatement(sql);
                    stmt.execute();
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                    attTabelaItens();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao Excluir" + e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Item");
        }
        attTabelaItens();
    }//GEN-LAST:event_btnExcluirItensActionPerformed

    private void btnEditarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarItensActionPerformed
        // TODO add your handling code here:
        if (tbItens1.getSelectedRow() != -1) {

            String indexComboBox = (String) cbCategoria1.getSelectedItem();

            if (indexComboBox.equals("Selecione")) {
                JOptionPane.showMessageDialog(null, "Selecione uma Categoria");
            } else {
                Itens objItem = new Itens();
                ItensDAO objItenDAO = new ItensDAO();

                objItem.setId_Item((int) tbItens1.getValueAt(tbItens1.getSelectedRow(), 0));
                objItem.setNome_Item(txtNomeItem1.getText());
                objItem.setDescricao_Item(taDescricaoItem1.getText());
                objItem.setCategoria_Item(indexComboBox);
                objItem.setEspecificacao_Item(txtEspecItem1.getText());

                objItenDAO.updateItens(objItem);

                txtNomeItem1.setText("");
                taDescricaoItem1.setText("");
                txtEspecItem1.setText("");
                cbCategoria1.setSelectedIndex(0);

                attTabelaItens();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_btnEditarItensActionPerformed

    private void btnAddItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItensActionPerformed
        // TODO add your handling code here:
        Itens objItens = new Itens();
        ItensDAO objItensDAO = new ItensDAO();

        String indexComboBox = (String) cbCategoria1.getSelectedItem();

        while (txtNomeItem1.getText().equals("") || txtEspecItem1.getText().equals("") || taDescricaoItem1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            break;
        }
        if (indexComboBox.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione uma categoria");
        } else {

            objItens.setNome_Item(txtNomeItem1.getText());
            objItens.setDescricao_Item(taDescricaoItem1.getText());
            objItens.setCategoria_Item(indexComboBox);
            objItens.setEspecificacao_Item(txtEspecItem1.getText());

            objItensDAO.save(objItens);
            JOptionPane.showMessageDialog(null, "Item '" + txtNomeItem1.getText() + "' foi cadastrado com sucesso !");
            attTabelaItens();
        }
        txtNomeItem1.setText("");
        taDescricaoItem1.setText("");
        cbCategoria1.setSelectedIndex(0);
        txtEspecItem1.setText("");
    }//GEN-LAST:event_btnAddItensActionPerformed

    private void tbItens1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItens1MouseClicked
        // TODO add your handling code here:
        if (tbItens1.getSelectedRow() != -1) {
            txtNomeItem1.setText(tbItens1.getValueAt(tbItens1.getSelectedRow(), 1).toString());
            taDescricaoItem1.setText(tbItens1.getValueAt(tbItens1.getSelectedRow(), 2).toString());
            cbCategoria1.setSelectedIndex(0);
            txtEspecItem1.setText(tbItens1.getValueAt(tbItens1.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tbItens1MouseClicked

    private void campoBuscaItensjTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaItensjTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaItensjTextField_pesqActionPerformed

    private void campoBuscaItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaItensKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaItensKeyPressed

    private void campoBuscaItensKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaItensKeyTyped

        try {
            String sql = "SELECT * FROM item WHERE nome_Item LIKE ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, "%" + campoBuscaItens.getText() + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbItens1.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_Item"),
                    rs.getString("nome_Item"),
                    rs.getString("descricao_Item"),
                    rs.getString("categoria_Item"),
                    rs.getString("especificacao_Item"),});
        }
        rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaItensKeyTyped

    private void campoBuscaUserjTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaUserjTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserjTextField_pesqActionPerformed

    private void campoBuscaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserKeyPressed

    private void campoBuscaUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyTyped
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM usu WHERE nome_Usu LIKE ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, "%" + campoBuscaUser.getText() + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbUsuarios.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_Usu"),
                    rs.getString("nome_Usu"),
                    rs.getString("senha_Usu"),
                    rs.getString("tipo_Usu")});
        }
        rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaUserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInvAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInvAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInvAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInvAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInvAdm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConfigItens;
    private javax.swing.JPanel PainelConfigUser;
    private javax.swing.JPanel PainelItens1;
    private javax.swing.JPanel PainelUsuarios;
    private javax.swing.JButton btnAddItens;
    private javax.swing.JButton btnAddUsu;
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnEditarItens;
    private javax.swing.JButton btnEditarUsu;
    private javax.swing.JButton btnExcluirItens;
    private javax.swing.JButton btnExcluirUsu;
    private javax.swing.JTextField campoBuscaItens;
    private javax.swing.JTextField campoBuscaUser;
    private javax.swing.JComboBox<String> cbCategoria1;
    private javax.swing.JComboBox<String> cbTipoUsu;
    private javax.swing.JLabel imgEB;
    private javax.swing.JLabel imgEB1;
    private javax.swing.JLabel imgEB2;
    private javax.swing.JLabel imgEB3;
    private javax.swing.JLabel imgEB4;
    private javax.swing.JLabel imgEBMedal;
    private javax.swing.JLabel imgPesq;
    private javax.swing.JLabel imgPesq1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCabeçalho;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbInventario;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel logoEBMini;
    private javax.swing.JTextArea taDescricaoItem1;
    private javax.swing.JTable tbItens1;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txtEspecItem1;
    private javax.swing.JTextField txtNomeItem1;
    private javax.swing.JTextField txtNomeUsu;
    private javax.swing.JTextField txtSenhaUsu;
    // End of variables declaration//GEN-END:variables

    private void attTabelaUsu() {

        try {

            String sql = "SELECT * FROM usu";
            PreparedStatement stmt = con.prepareStatement(sql);

            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbUsuarios.getModel();

            model.setNumRows(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_Usu"),
                    rs.getString("nome_Usu"),
                    rs.getString("senha_Usu"),
                    rs.getString("tipo_Usu")});

            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Atualizar dados" + e);
        }
    }

    private void attTabelaItens() {

        try {

            String sql = "SELECT * FROM item";
            PreparedStatement stmt = con.prepareStatement(sql);

            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbItens1.getModel();

            model.setNumRows(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_Item"),
                    rs.getString("nome_Item"),
                    rs.getString("descricao_Item"),
                    rs.getString("categoria_Item"),
                    rs.getString("especificacao_Item")});

            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Atualizar dados" + e);
        }
    }
}
