/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import connection.ConnectionFactory;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.bean.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author PICHAU
 */
public class LoginUsu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Connection con = null;
    
    public LoginUsu() {
        initComponents();
        con = ConnectionFactory.getConnection();
        

        imagemEB2.setEnabled(false);
    }
    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();


            Color color1 = new Color(21, 170, 30); //Cor de cima
            Color color2 = new Color(10, 75, 15);  //Cor de baixo
            GradientPaint gp = new GradientPaint(0, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFundo = new jPanelGradient();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        cbTipoUser = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();
        imagemEB2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logoEb = new javax.swing.JLabel();
        ImagemEB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISCOFIS");

        PainelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PainelFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 589, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA DE CONTROLE FISICO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PainelFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 230, 20));

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("SISCOFIS");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PainelFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 230, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 52)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 60));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOME :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SENHA :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        jPanel4.add(txtNomeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 195, 30));
        jPanel4.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 195, 30));

        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, 30));

        cbTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Admin", "Usuario" }));
        jPanel4.add(cbTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 95, 30));

        btnExit.setText("SAIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 60, 30));

        imagemEB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EB.jpg"))); // NOI18N
        imagemEB2.setText("jLabel7");
        jPanel4.add(imagemEB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, -30, 770, 480));

        PainelFundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 360, 450));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Versão 0.1");
        PainelFundo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        logoEb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo EB_1.png"))); // NOI18N
        logoEb.setMaximumSize(new java.awt.Dimension(200, 200));
        logoEb.setMinimumSize(new java.awt.Dimension(100, 100));
        logoEb.setPreferredSize(new java.awt.Dimension(200, 200));
        PainelFundo.add(logoEb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 140, 140));

        ImagemEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EB.jpg"))); // NOI18N
        PainelFundo.add(ImagemEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        Usuario objUsu = new Usuario();

        String indexComboBox = (String) cbTipoUser.getSelectedItem();
        while (txtNomeLogin.getText().equals("") || txtSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            break;
        }
        while (indexComboBox.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um tipo de Usuario");
            break;
        }

        objUsu.setNome_Usu(txtNomeLogin.getText());
        objUsu.setSenha_Usu(txtSenha.getText());
        objUsu.setTipo_Usu((String) cbTipoUser.getSelectedItem());
        
        UsuarioDAO objUsuDAO = new UsuarioDAO();
        ResultSet rsUsuDAO = objUsuDAO.autenticacaoUsuario(objUsu);
        
        try {
            if (rsUsuDAO.next()) {
                String dadoCbTipo = objUsu.getTipo_Usu();
                if (dadoCbTipo == "Admin") {
                    TelaInvAdm telaAdm = new TelaInvAdm();
                    telaAdm.setVisible(true);
                    this.dispose();
                } else if (dadoCbTipo == "Usuario") {

                    TelaInvUsu telaUser = new TelaInvUsu();
                    telaUser.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email ou Senha Incorretos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no Login" + ex);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemEB;
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cbTipoUser;
    private javax.swing.JLabel imagemEB2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logoEb;
    private javax.swing.JTextField txtNomeLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
